### ISSUE TITLE
screenshot in readme may be wrong.

### ISSUE THREAD

**Issue by iysheng** [dracula/st#1]
I use patch ``st-dracula-0.8.5.diff``with st. But I do neofech under st. I get picture as below:
![](https://s3.bmp.ovh/imgs/2023/06/13/1e3edbb71addf7a2.png)
There we can see the fedora log in box is pink color, it's obviously different with the screen in README.md .

**Comment by gildasio** [comment]
Yeah it's pretty different as I know because `neofetch` acts different in different distros. Some examples:

![Debian](https://github.com/dracula/st/assets/6231305/de2de2b8-042d-41fd-b9cc-8cbea6b601da)

![Ubuntu](https://github.com/dracula/st/assets/6231305/e80a7c49-f5d1-4606-a734-ea35b1ce303e)

![Kali](https://github.com/dracula/st/assets/6231305/94521133-5594-4646-8ea1-543961ba3e57)

**Comment by gildasio** [comment]
BTW these previous examples doesn't use st-dracula. Let me use st-dracula and print Fedora and Arch logo:

![Fedora and Arch](https://github.com/dracula/st/assets/6231305/2246ff96-c44b-4aeb-8d29-f5e399615c63)

**Comment by iysheng** [comment]
Ok,
